### PR TITLE
updates bindings to v2.8.3

### LINKED ISSUE #3: Update bindings to v2.8.2
I've recently hit a bug with the library that has been fixed with v2.8.2.
I would highly appreciate if the bindings could be updated to that version

### PR DESCRIPTION
**Pull request by tipa**
fixes #3

### CODE REVIEW

**Comment by tuyen-vuduc** [comment]
@tipa Could you please ensure API definition is aligned with latest version?

**Comment by tipa** [comment]
Please see the updated APIDefinition.cs
I added the new bindings and also fixed some existing ones.
Hope it doesn't break anything, everything is still working fine in my project

**Comment by tipa** [comment]
Thanks! Will there be a new NuGet package?

**Comment by tuyen-vuduc** [comment]
@tipa Thanks a lot for your contribution. New version is being published. You should be able to install it from Nuget in about 1 hour.

Cheers.

**Comment by tipa** [comment]
Very cool - thanks a lot for keeping up support for those bindings!

**Comment by tuyen-vuduc** [comment]
You're welcome! If you have times, it would be very appreciated to upgrade the sample app as well :) .

**Pull request merged**
