### PR TITLE
Updated ApiDefinitions - fix for "Non-public API usage"

### PR DESCRIPTION
**Pull request by tipa**
I found out that the current bindings would cause problems when uploading a binary to the Apple App Store. The app got rejected with "Non-public API usage".
I fixed these (and more) problems with the updates bindings in this pull request.
Would be fantastic if it could get merged and a new NuGet package be created. Thanks in advance!

### CODE REVIEW

**Comment by tuyen-vuduc** [comment]
@tipa Great!

Did you have to make any changes to the native lib?

**Comment by tipa** [comment]
No, the problem was that there were outdated header files when the Bindings with Objective Sharpie took place. Now the correct header files were used.

I did a recompilation though and one of the library binaries changed, not sure if that matters

**Comment by tuyen-vuduc** [comment]
```
 error MT5209 : Native linking error : warning: ignoring file /Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/obj/iPhone/Release/mtouch-cache/FSCalendar.framework/FSCalendar, missing required architecture armv7 in file /Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/obj/iPhone/Release/mtouch-cache/FSCalendar.framework/FSCalendar (2 slices) [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendar. The symbol '_OBJC_CLASS_$_FSCalendar' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarAppearance. The symbol '_OBJC_CLASS_$_FSCalendarAppearance' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarBlankCell. The symbol '_OBJC_CLASS_$_FSCalendarBlankCell' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarCalculator. The symbol '_OBJC_CLASS_$_FSCalendarCalculator' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarCell. The symbol '_OBJC_CLASS_$_FSCalendarCell' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarCollectionView. The symbol '_OBJC_CLASS_$_FSCalendarCollectionView' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarCollectionViewLayout. The symbol '_OBJC_CLASS_$_FSCalendarCollectionViewLayout' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarEventIndicator. The symbol '_OBJC_CLASS_$_FSCalendarEventIndicator' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarHeaderCell. The symbol '_OBJC_CLASS_$_FSCalendarHeaderCell' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarHeaderLayout. The symbol '_OBJC_CLASS_$_FSCalendarHeaderLayout' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarHeaderTouchDeliver. The symbol '_OBJC_CLASS_$_FSCalendarHeaderTouchDeliver' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarHeaderView. The symbol '_OBJC_CLASS_$_FSCalendarHeaderView' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarStickyHeader. The symbol '_OBJC_CLASS_$_FSCalendarStickyHeader' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarTransitionAttributes. The symbol '_OBJC_CLASS_$_FSCalendarTransitionAttributes' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarTransitionCoordinator. The symbol '_OBJC_CLASS_$_FSCalendarTransitionCoordinator' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FSCalendarWeekdayView. The symbol '_OBJC_CLASS_$_FSCalendarWeekdayView' could not be found in any of the libraries or frameworks linked with your application. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_FSCalendarCell. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  MTOUCH : error MT5202: Native linking failed. Please review the build log. [/Volumes/ws/bindings/fscalendar-ios-binding/FSCalendarQS/FSCalendarQS.csproj]
  ```
  
@tipa   Have you checked the sample app?

**Comment by tipa** [comment]
> missing required architecture armv7

I have built the library in arm64 + x86_64 - afaik armv7 is pretty old and not needed nowadays.

> @tipa Have you checked the sample app?

Yes I have looked at it and it still compiles, but it would need a larger overhaul. E.g. it's not adapted for Dark Theme and most of the buttons don't work / navigate to an empty View controller

**Pull request merged**
